/**
 * Tests for spine manifest validation.
 *
 * Ensures specs/_doc_spine.yml:
 * - Has all required top-level fields
 * - References only paths that exist on disk
 * - Does not accumulate orphaned spec files
 */

import * as fs from 'fs';
import * as path from 'path';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';
import { validateSpineManifest, extractPathsFromSpine, validateSpineSchema, parseSpineSections } from '../scripts/validate-spine-manifest';

// Anchored to import.meta.url, not process.cwd(): a jest worker's cwd can be
// moved by a module-load side effect (whisper-node chdir — see
// tests/__mocks__/whisper-node.ts); a cwd anchor then reads the manifest as
// absent and these tests silently it.skip instead of running.
const REPO_ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const SPINE_PATH = path.join(REPO_ROOT, 'specs', '_doc_spine.yml');
const SPINE_EXISTS = fs.existsSync(SPINE_PATH);

describe('Spine Manifest Validation', () => {
  describe('validateSpineManifest', () => {
    (SPINE_EXISTS ? it : it.skip)('should return valid=true for current manifest', () => {
      const result = validateSpineManifest();
      expect(result.valid).toBe(true);
      expect(result.errors).toHaveLength(0);
    });

    (SPINE_EXISTS ? it : it.skip)('should check all referenced paths exist', () => {
      const result = validateSpineManifest();
      expect(result.checkedPaths).toBeGreaterThan(0);

      // Every path should exist — no errors
      expect(result.errors.filter((e) => e.includes('does not exist'))).toHaveLength(0);
    });

    (SPINE_EXISTS ? it : it.skip)('should have required top-level fields', () => {
      const result = validateSpineManifest();
      expect(result.errors.filter((e) => e.includes('Missing required field'))).toHaveLength(0);
    });

    (SPINE_EXISTS ? it : it.skip)('should detect orphaned spec files as warnings (not errors)', () => {
      const result = validateSpineManifest();
      // Orphaned files are warnings, not blocking errors
      // The current manifest may have some orphans — that's OK as long as they're reported
      for (const orphan of result.orphanedFiles) {
        expect(result.warnings.some((w) => w.includes(orphan))).toBe(true);
      }
    });

    // Regression: specs/_doc_spine.yml is an auto-generated, gitignored
    // artifact (regenerated by the external make-run tool — see .gitignore),
    // so on a clean checkout and in CI (which never runs make-run) it is
    // legitimately ABSENT. The legacy validator returned valid:false on
    // absence, which made `npm run spine:validate` exit 1 and broke the
    // `spine-validate` CI gate — a required dependency of `build` and
    // `all-checks-pass` — on every clean checkout. Absence is the expected
    // "nothing to validate" state: it must SKIP cleanly (valid=true) with a
    // transparent notice, not fail. Runs regardless of whether a local
    // manifest happens to exist, via an explicit non-existent path override.
    it('SKIPS cleanly (valid=true, skipped=true) when the manifest is absent', () => {
      const result = validateSpineManifest(
        path.join(REPO_ROOT, '__nonexistent_spine__', '_doc_spine.yml'),
      );
      expect(result.valid).toBe(true);
      expect(result.skipped).toBe(true);
      expect(result.errors).toHaveLength(0);
      expect(result.checkedPaths).toBe(0);
      // Transparent (non-silent) skip carries a human-readable notice.
      expect(result.warnings.length).toBeGreaterThan(0);
      expect(result.warnings.some((w) => /SKIPPED/i.test(w))).toBe(true);
    });
  });

  describe('extractPathsFromSpine', () => {
    it('should extract path values from list items', () => {
      const yaml = `
entrypoints:
- path: README.md
  audience: contributor
- path: AGENTS.md
  audience: ai-agent
`;
      const paths = extractPathsFromSpine(yaml);
      expect(paths).toContain('README.md');
      expect(paths).toContain('AGENTS.md');
    });

    it('should extract constitution path', () => {
      const yaml = `constitution: SYSTEM_CONSTITUTION.md\npurpose: null`;
      const paths = extractPathsFromSpine(yaml);
      expect(paths).toContain('SYSTEM_CONSTITUTION.md');
    });

    it('should handle null constitution gracefully', () => {
      const yaml = `constitution: null\npurpose: null`;
      const paths = extractPathsFromSpine(yaml);
      expect(paths).not.toContain('null');
    });

    it('should deduplicate paths', () => {
      const yaml = `
entrypoints:
- path: README.md
system_design:
- path: README.md
`;
      const paths = extractPathsFromSpine(yaml);
      expect(paths.filter((p) => p === 'README.md')).toHaveLength(1);
    });

    it('should extract nested children paths', () => {
      const yaml = `
system_design:
- path: architecture.md
  children:
  - path: acceptance-criteria.md
  - path: dataflow.md
`;
      const paths = extractPathsFromSpine(yaml);
      expect(paths).toContain('architecture.md');
      expect(paths).toContain('acceptance-criteria.md');
      expect(paths).toContain('dataflow.md');
    });
  });

  (SPINE_EXISTS ? describe : describe.skip)('Spine manifest file structure', () => {
    let spineContent: string;

    beforeAll(() => {
      spineContent = fs.readFileSync(SPINE_PATH, 'utf-8');
    });

    (SPINE_EXISTS ? it : it.skip)('should exist as a file', () => {
      expect(fs.existsSync(SPINE_PATH)).toBe(true);
    });

    it('should have constitution field', () => {
      expect(spineContent).toMatch(/^constitution:\s*\S+/m);
    });

    it('should have entrypoints section', () => {
      expect(spineContent).toMatch(/^entrypoints:/m);
    });

    it('should have system_design section', () => {
      expect(spineContent).toMatch(/^system_design:/m);
    });

    it('should have at least one entrypoint with audience', () => {
      expect(spineContent).toMatch(/audience:\s*\S+/);
    });

    it('should reference SYSTEM_CONSTITUTION.md', () => {
      expect(spineContent).toContain('SYSTEM_CONSTITUTION.md');
    });

    it('should reference architecture.md in system_design', () => {
      expect(spineContent).toContain('architecture.md');
    });

    it('should not contain task file references (TASK-*.md)', () => {
      // Per spine rules, TASK-*.md files should NOT be in the spine
      expect(spineContent).not.toMatch(/TASK-\d+\.md/);
    });
  });

  (SPINE_EXISTS ? describe : describe.skip)('All spine-referenced paths exist on disk', () => {
    it('should verify every path exists', () => {
      const content = fs.readFileSync(SPINE_PATH, 'utf-8');
      const paths = extractPathsFromSpine(content);

      const missing: string[] = [];
      for (const relPath of paths) {
        const rootPath = path.join(REPO_ROOT, relPath);
        const specsPath = path.join(REPO_ROOT, 'specs', relPath);
        if (!fs.existsSync(rootPath) && !fs.existsSync(specsPath)) {
          missing.push(relPath);
        }
      }

      expect(missing).toEqual([]);
    });
  });

  describe('validateSpineSchema', () => {
    (SPINE_EXISTS ? it : it.skip)('should return no errors for the current spine manifest', () => {
      const content = fs.readFileSync(SPINE_PATH, 'utf-8');
      const errors = validateSpineSchema(content);
      expect(errors).toEqual([]);
    });

    it('should detect entrypoint missing path', () => {
      const yaml = `entrypoints:\n  - audience: contributor\n`;
      const errors = validateSpineSchema(yaml);
      expect(errors.some((e) => e.includes("missing required key 'path'"))).toBe(true);
    });

    it('should detect entrypoint missing audience', () => {
      const yaml = `entrypoints:\n  - path: README.md\n`;
      const errors = validateSpineSchema(yaml);
      expect(errors.some((e) => e.includes("missing required key 'audience'"))).toBe(true);
    });

    it('should detect system_design item missing path', () => {
      const yaml = `system_design:\n  - children:\n`;
      const errors = validateSpineSchema(yaml);
      expect(errors.some((e) => e.includes("missing required key 'path'"))).toBe(true);
    });

    it('should detect reference missing doc', () => {
      const yaml = `references:\n  - referenced_by:\n    - architecture.md\n`;
      const errors = validateSpineSchema(yaml);
      expect(errors.some((e) => e.includes("missing required key 'doc'"))).toBe(true);
    });

    it('should accept a well-formed manifest', () => {
      const yaml = [
        'constitution: SYSTEM_CONSTITUTION.md',
        'purpose: null',
        'entrypoints:',
        '  - path: README.md',
        '    audience: contributor',
        'system_design:',
        '  - path: architecture.md',
        '    children:',
        '      - path: acceptance-criteria.md',
        'references:',
        '  - doc: api-endpoints.md',
        '    referenced_by:',
        '      - architecture.md',
      ].join('\n');
      const errors = validateSpineSchema(yaml);
      expect(errors).toEqual([]);
    });

    (SPINE_EXISTS ? it : it.skip)('should be integrated into validateSpineManifest results', () => {
      const result = validateSpineManifest();
      expect(result.schemaErrors).toBeDefined();
      expect(Array.isArray(result.schemaErrors)).toBe(true);
      // Current manifest should have zero schema errors
      expect(result.schemaErrors).toHaveLength(0);
    });

    it('should detect duplicate paths across sections', () => {
      const yaml = [
        'constitution: SYSTEM_CONSTITUTION.md',
        'purpose: null',
        'entrypoints:',
        '  - path: README.md',
        '    audience: contributor',
        'system_design:',
        '  - path: README.md',
        'references:',
        '  - doc: api-endpoints.md',
        '    referenced_by:',
        '      - architecture.md',
      ].join('\n');
      const errors = validateSpineSchema(yaml);
      expect(errors.some((e) => e.includes("Duplicate path 'README.md'") && e.includes('2 times'))).toBe(true);
    });

    it('should detect duplicate paths within the same section', () => {
      const yaml = [
        'entrypoints:',
        '  - path: README.md',
        '    audience: contributor',
        '  - path: README.md',
        '    audience: ai-agent',
      ].join('\n');
      const errors = validateSpineSchema(yaml);
      expect(errors.some((e) => e.includes("Duplicate path 'README.md'"))).toBe(true);
    });

    it('should detect invalid audience value', () => {
      const yaml = [
        'entrypoints:',
        '  - path: README.md',
        '    audience: invalid-role',
      ].join('\n');
      const errors = validateSpineSchema(yaml);
      expect(errors.some((e) => e.includes("invalid audience 'invalid-role'"))).toBe(true);
    });

    it('should accept all valid audience values', () => {
      const yaml = [
        'entrypoints:',
        '  - path: README.md',
        '    audience: contributor',
        '  - path: AGENTS.md',
        '    audience: ai-agent',
        '  - path: CLAUDE.md',
        '    audience: ai-agent-claude',
        '  - path: GEMINI.md',
        '    audience: ai-agent-gemini',
      ].join('\n');
      const errors = validateSpineSchema(yaml);
      // Should have no audience errors (may have duplicate path errors since these aren't real files)
      expect(errors.filter((e) => e.includes('invalid audience'))).toHaveLength(0);
    });

    it('should detect duplicate paths in children', () => {
      const yaml = [
        'system_design:',
        '  - path: architecture.md',
        '    children:',
        '      - path: dataflow.md',
        '      - path: dataflow.md',
      ].join('\n');
      const errors = validateSpineSchema(yaml);
      expect(errors.some((e) => e.includes("Duplicate path 'dataflow.md'") && e.includes('2 times'))).toBe(true);
    });

    it('should not report duplicates for unique paths', () => {
      const yaml = [
        'entrypoints:',
        '  - path: README.md',
        '    audience: contributor',
        'system_design:',
        '  - path: architecture.md',
        '    children:',
        '      - path: dataflow.md',
        'references:',
        '  - doc: api-endpoints.md',
        '    referenced_by:',
        '      - architecture.md',
      ].join('\n');
      const errors = validateSpineSchema(yaml);
      expect(errors.filter((e) => e.includes('Duplicate path'))).toHaveLength(0);
    });

    // --- New: cross-reference validation ---

    it('should detect referenced_by pointing to non-existent system_design path', () => {
      const yaml = [
        'entrypoints:',
        '  - path: README.md',
        '    audience: contributor',
        'system_design:',
        '  - path: architecture.md',
        'references:',
        '  - doc: api-endpoints.md',
        '    referenced_by:',
        '      - nonexistent.md',
      ].join('\n');
      const errors = validateSpineSchema(yaml);
      expect(errors.some((e) => e.includes("referenced_by 'nonexistent.md' not found in system_design"))).toBe(true);
    });

    it('should accept referenced_by that matches a system_design child path', () => {
      const yaml = [
        'entrypoints:',
        '  - path: README.md',
        '    audience: contributor',
        'system_design:',
        '  - path: architecture.md',
        '    children:',
        '      - path: dataflow.md',
        'references:',
        '  - doc: api-endpoints.md',
        '    referenced_by:',
        '      - dataflow.md',
      ].join('\n');
      const errors = validateSpineSchema(yaml);
      expect(errors.filter((e) => e.includes('referenced_by') && e.includes('not found'))).toHaveLength(0);
    });

    it('should detect reference missing referenced_by entirely', () => {
      const yaml = [
        'entrypoints:',
        '  - path: README.md',
        '    audience: contributor',
        'system_design:',
        '  - path: architecture.md',
        'references:',
        '  - doc: api-endpoints.md',
      ].join('\n');
      const errors = validateSpineSchema(yaml);
      expect(errors.some((e) => e.includes("missing or empty 'referenced_by'"))).toBe(true);
    });

    // --- New: empty section validation ---

    it('should detect empty entrypoints section', () => {
      const yaml = [
        'entrypoints:',
        'system_design:',
        '  - path: architecture.md',
        'references:',
        '  - doc: api-endpoints.md',
        '    referenced_by:',
        '      - architecture.md',
      ].join('\n');
      const errors = validateSpineSchema(yaml);
      expect(errors.some((e) => e.includes('entrypoints section is empty'))).toBe(true);
    });

    it('should detect empty system_design section', () => {
      const yaml = [
        'entrypoints:',
        '  - path: README.md',
        '    audience: contributor',
        'system_design:',
        'references:',
        '  - doc: api-endpoints.md',
        '    referenced_by:',
        '      - architecture.md',
      ].join('\n');
      const errors = validateSpineSchema(yaml);
      expect(errors.some((e) => e.includes('system_design section is empty'))).toBe(true);
    });

    // --- New: path format validation ---

    it('should detect path with backslashes', () => {
      const yaml = [
        'entrypoints:',
        '  - path: README\\md',
        '    audience: contributor',
        'system_design:',
        '  - path: architecture.md',
        'references:',
        '  - doc: api-endpoints.md',
        '    referenced_by:',
        '      - architecture.md',
      ].join('\n');
      const errors = validateSpineSchema(yaml);
      expect(errors.some((e) => e.includes('backslashes'))).toBe(true);
    });

    it('should detect absolute path', () => {
      const yaml = [
        'entrypoints:',
        '  - path: /absolute/path.md',
        '    audience: contributor',
        'system_design:',
        '  - path: architecture.md',
        'references:',
        '  - doc: api-endpoints.md',
        '    referenced_by:',
        '      - architecture.md',
      ].join('\n');
      const errors = validateSpineSchema(yaml);
      expect(errors.some((e) => e.includes('absolute'))).toBe(true);
    });

    (SPINE_EXISTS ? it : it.skip)('should pass the actual spine manifest with new validations', () => {
      const content = fs.readFileSync(SPINE_PATH, 'utf-8');
      const errors = validateSpineSchema(content);
      // The real manifest should have zero schema errors including new checks
      expect(errors).toEqual([]);
    });
  });

  describe('parseSpineSections', () => {
    it('should parse entrypoints with path and audience', () => {
      const yaml = [
        'entrypoints:',
        '  - path: README.md',
        '    audience: contributor',
        '  - path: AGENTS.md',
        '    audience: ai-agent',
      ].join('\n');
      const sections = parseSpineSections(yaml);
      expect(sections.entrypoints).toHaveLength(2);
      expect(sections.entrypoints[0].path).toBe('README.md');
      expect(sections.entrypoints[0].audience).toBe('contributor');
      expect(sections.entrypoints[1].path).toBe('AGENTS.md');
    });

    it('should parse system_design with children', () => {
      const yaml = [
        'system_design:',
        '  - path: architecture.md',
        '    children:',
        '      - path: acceptance-criteria.md',
        '      - path: dataflow.md',
      ].join('\n');
      const sections = parseSpineSections(yaml);
      expect(sections.systemDesign).toHaveLength(1);
      expect(sections.systemDesign[0].path).toBe('architecture.md');
      expect(sections.systemDesign[0].children).toHaveLength(2);
      expect(sections.systemDesign[0].children![0].path).toBe('acceptance-criteria.md');
      expect(sections.systemDesign[0].children![1].path).toBe('dataflow.md');
    });

    it('should parse references with doc key', () => {
      const yaml = [
        'references:',
        '  - doc: api-endpoints.md',
        '    referenced_by:',
        '      - architecture.md',
      ].join('\n');
      const sections = parseSpineSections(yaml);
      expect(sections.references).toHaveLength(1);
      expect(sections.references[0].doc).toBe('api-endpoints.md');
    });

    (SPINE_EXISTS ? it : it.skip)('should parse the actual spine manifest', () => {
      const content = fs.readFileSync(SPINE_PATH, 'utf-8');
      const sections = parseSpineSections(content);
      expect(sections.entrypoints.length).toBeGreaterThanOrEqual(3);
      expect(sections.systemDesign.length).toBeGreaterThanOrEqual(1);
      // All entrypoints should have both path and audience
      sections.entrypoints.forEach((ep) => {
        expect(ep.path).toBeDefined();
        expect(ep.audience).toBeDefined();
      });
    });
  });
});
