// Bundle Optimization Guide
// Generated by Claude Code Performance Optimizer

export const bundleOptimizations = {
  // 1. Import specific functions instead of entire libraries
  'lodash': 'import { debounce } from "lodash/debounce"',
  'lucide-react': 'import { Upload, FileAudio, CheckCircle2 } from "lucide-react"',
  'date-fns': 'import { format } from "date-fns/format"',

  // 2. Use dynamic imports for heavy components
  dynamicImports: [
    'const DiagramRenderer = lazy(() => import("./DiagramRenderer"))',
    'const VideoRenderer = lazy(() => import("./VideoRenderer"))',
    'const ProductionDashboard = lazy(() => import("./ProductionDashboard"))'
  ],

  // 3. Preload critical components
  preloadComponents: [
    'AudioUploader',
    'ProcessingStatus',
    'DiagramPreview'
  ]
};
