/**
 * Pins the retirement of `AdvancedVisualEngine` (defect class: LATENT/DEAD code
 * with an uncapped monotonic-key `qualityMetrics` Map and ZERO production
 * callers).
 *
 * The type contracts in advanced-visual-engine.ts are LIVE — they are consumed
 * by src/export/production-exporter.ts and its tests — so the module stays
 * types-only. This test pins BOTH facts:
 *
 *   1. the runtime engine/singleton must NOT come back (dead-code regression),
 *   2. the type exports must keep compiling against a representative shape
 *      (tsc --noEmit is part of the verification loop, so a type-level
 *      assignment failure fails the build).
 */

import * as moduleExports from '../advanced-visual-engine';
import type {
  VisualStyle,
  EnhancedSceneGraph,
  AnimationSequence,
  BackgroundConfig,
  WatermarkConfig,
  RenderOptions,
} from '../advanced-visual-engine';
import type { SceneGraph } from '@stv/core/types/diagram';
import * as visualization from '../index';

describe('advanced-visual-engine: types-only module contract', () => {
  it('module exports ONLY types — no runtime engine class or singleton', () => {
    // A types-only ES module compiles to an empty runtime namespace.
    expect(Object.keys(moduleExports)).toEqual([]);
  });

  it('engine class/singleton are not re-exported from the @/visualization barrel', () => {
    expect((visualization as Record<string, unknown>).AdvancedVisualEngine).toBeUndefined();
    expect((visualization as Record<string, unknown>).advancedVisualEngine).toBeUndefined();
  });

  it('LIVE type contracts still type-check against production-exporter shapes', () => {
    // Mirrors how src/export/production-exporter.ts uses these types
    // (PreparedScene extends EnhancedSceneGraph; RenderOptions param object).
    const style: VisualStyle = {
      theme: 'modern',
      colorScheme: 'blue',
      animation: 'smooth',
      nodeStyle: 'rounded',
      edgeStyle: 'curved',
      fontSize: 'medium',
      spacing: 'normal',
    };
    const animation: AnimationSequence = {
      type: 'entrance',
      target: 'node-1',
      timing: { delay: 0, duration: 600, easing: 'ease-out' },
      properties: { opacity: { from: 0, to: 1 } },
    };
    const background: BackgroundConfig = {
      type: 'solid',
      primary: '#FFFFFF',
      opacity: 1,
    };
    const watermark: WatermarkConfig = {
      text: 'Generated by Speech-to-Visuals AI',
      position: 'bottom-right',
      opacity: 0.3,
      fontSize: 12,
    };
    const scene: SceneGraph = {
      type: 'flow',
      nodes: [{ id: 'n1', label: 'Start' }],
      edges: [{ from: 'n1', to: 'n1' }],
    } as SceneGraph;
    const enhanced: EnhancedSceneGraph = {
      ...scene,
      visualStyle: style,
      animations: [animation],
      background,
      watermark,
    };
    const options: RenderOptions = {
      width: 1920,
      height: 1080,
      fps: 30,
      quality: 'high',
      format: 'mp4',
      includeAudio: true,
      exportCaption: true,
    };

    expect(enhanced.animations).toHaveLength(1);
    expect(options.quality).toBe('high');
  });
});
