/**
 * UUID v4 validation — single source for the API layer (single-source round 12).
 *
 * The REST routes (batch, export, export-jobs) and the websocket handler all
 * validate path/event jobIds against the SAME contract: "the id must be a
 * UUID v4 as generated by uuidv4()". Four hand-rolled copies of this regex
 * meant one drift (dropping the `[89ab]` variant nibble, the `/i` flag, or a
 * character class) would make the same jobId 400-reject on one endpoint while
 * passing on another. Import this regex instead of redeclaring it.
 */

// UUID v4: version nibble 4, variant nibble [89ab], case-insensitive.
export const UUID_V4_RE = /^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;
