/**
 * REQ-234: Export Artifact Download Routes (Phase 101)
 *
 * REST endpoint for downloading stored export artifacts:
 * - GET /api/v1/export/artifacts/:artifactId/download?token=<uuid>
 *
 * Validates the download URL token and expiry, then returns artifact data
 * with appropriate Content-Type and Content-Disposition headers.
 */

import { Router, Request, Response } from 'express';
import { ExportArtifactStore } from '../../export/export-artifact-store';
import { logger } from '../../utils/logger';

// UUID v4 validation regex
const UUID_V4_RE = /^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;

// Format to MIME type mapping
const FORMAT_MIME: Record<string, string> = {
  mp4: 'video/mp4',
  webm: 'video/webm',
  gif: 'image/gif',
  apng: 'image/apng',
  'interactive-html': 'text/html',
  'pdf-animated': 'application/pdf',
  'svg-animated': 'image/svg+xml',
  'json-lottie': 'application/json',
  json: 'application/json',
  svg: 'image/svg+xml',
  pdf: 'application/pdf',
  html: 'text/html',
};

export function createExportRouter(artifactStore: ExportArtifactStore): Router {
  const router = Router();

  /**
   * GET /api/v1/export/artifacts/:artifactId/download
   *
   * Query params:
   *   - token (required): Download URL token generated by ExportArtifactStore.generateDownloadUrl()
   *
   * Returns artifact binary data with appropriate headers.
   */
  router.get('/artifacts/:artifactId/download', (req: Request, res: Response) => {
    const { artifactId } = req.params;
    const token = req.query.token as string | undefined;

    // Validate artifactId format
    if (!artifactId || !UUID_V4_RE.test(artifactId)) {
      res.status(400).json({
        success: false,
        error: {
          code: 'VALIDATION_ERROR',
          message: 'Invalid artifactId format (expected UUID v4)',
        },
      });
      return;
    }

    // Validate token presence
    if (!token || !UUID_V4_RE.test(token)) {
      res.status(400).json({
        success: false,
        error: {
          code: 'VALIDATION_ERROR',
          message: 'Missing or invalid download token',
        },
      });
      return;
    }

    // Resolve download URL (validates token + expiry)
    const artifact = artifactStore.resolveDownloadUrl(artifactId, token);
    if (!artifact) {
      res.status(404).json({
        success: false,
        error: {
          code: 'ARTIFACT_NOT_FOUND',
          message: 'Artifact not found, token invalid, or download URL expired',
        },
      });
      return;
    }

    // Determine content type
    const contentType = FORMAT_MIME[artifact.format] || 'application/octet-stream';
    const filename = `export-${artifactId}.${artifact.format}`;

    logger.info(`[ExportRouter] Downloading artifact ${artifactId} (${artifact.format}, ${artifact.sizeBytes} bytes)`);

    res.setHeader('Content-Type', contentType);
    res.setHeader('Content-Disposition', `attachment; filename="${filename}"`);
    res.setHeader('Content-Length', artifact.sizeBytes);
    res.setHeader('X-Artifact-Id', artifactId);
    res.send(Buffer.from(artifact.data));
  });

  return router;
}
